language: node_js
node_js:
  - 0.8
  - 0.10
  - 0.11

notifications:
  email:
    - travis@nodejitsu.com
  irc: "irc.freenode.org#nodejitsu"

services:
  - couchdb

before_script:
  - curl -X PUT localhost:5984/myapp_test